E-Warren/Tappt_Group8

README.md
this was suggested by renu in the comments of our proposal slides submission (canvas)
=> add age note in title line

app/login.tsx
Other login options has been removed, Google API has been implemented in our login page after login it redirect to index , It have not connected the database data store yet.
=> Explore Google API & how we want to implement it in our project

backend/backend-server.js, backend/backend_connection.js, backend/package-lock.json, backend/package.json
this contains all necessary files (so far) to run backend. So far, there is one connection to frontend (found in backend-server.js, first get function). 
*** please accept the first branch i've made (initializing the backend folder) below *** before accepting this one
=> added REST API and database connection for card decks

backend/README.md, backend/backend-server.js, backend/backend_connection.js, backend/package-lock.json, backend/package.json
for REST API and database connection for card decks
=> reupload of backend

backend/backend-server.js, backend/package-lock.json, backend/package.json
2.27.25
Database work and API calls as they relate to login/signup.
=> Backend files for login/signup commit

app/createdecks.tsx, app/view-decks.tsx, backend/backend-server.js
added frontend and backend connections for create and view decks.
=> added create/view decks connections

app/createdecks.tsx, backend/backend-server.js
Patched the duplicate decks bug in the backend. Cleaned up createdecks.tsx to only say deck creation is successful if backend sends a successful code.
=> Duplicate deck patch

app/createdecks.tsx
3/4: removed upload images from create decks page
=> removed upload images from create decks page

app/login.tsx, backend/README.md, backend/backend-server.js
The frontend and backend README changed due to the package. Google login functionality works well, and the manually temp logout button was added to remove async-storage data. Until you click the logout button, it is still a login status (your information will be shown on the login page). Make sure that you click the logout for future Google logins for now.  
After logging in with Google, the page moves to the view deck page. 
If you have any questions, please let me know.
=> Google login connected with server

app/login.tsx, package-lock.json, package.json
I deleted the information shown after login on to the sign-in page and updated the JSON file for the package dependency
=> Google login updates

app/answerchoices.tsx, app/createdecks.tsx, app/index.tsx, app/view-decks.tsx
updates to task #73 checkboxes and task #65 student side answer choices
=> checkboxes & student side answer choices

app/studentClicks.tsx, app/useWebSocketStore.ts
3/30/25: Completed click count feature (#79). Needs to be routed (#68) and then we may begin leaderboard work (#80).
Connects to websocket and updates student state. Listens for clicks and/or spacebar presses ONLY when user is on the "studentClicks.tsx" page. Resets upon reload (breaks websocket connection?). Small bug when moving back via arrow keys (counts exactly one bonus click)... this should not be an issue in-game since we're not using back-arrow navigation.
=> Integrating basic click count feature

app/_layout.tsx, app/endgame.tsx, app/index.tsx, app/roundend.tsx
Completed the Teacher side frontend for the end of round as well as the student side frontend for the end of the game.
=> Student side end-game screen and Teacher side end-round screen

app/index.tsx, app/questiontimer.tsx, app/reading.tsx, app/waiting.tsx
updates for task #63: teacher-side reading screen, task #64: teacher side question and timer screen, & task #66: student side answer received screen
=> task #63, task #64, & task #66

app/_layout.tsx, app/answerchoices.tsx, app/index.tsx, app/studentWaiting.tsx, app/teacherwaiting.tsx, app/useWebSocketStore.ts, app/view-decks.tsx, app/webSocketService.ts, backend/backend-server.js
added the code where students can answer questions for a game hosted by the teacher through socket work. 
how it works is when the teacher presses the let's go button, students in the game lobby are directed to the student-question-answer screen, where they can click their answers and it'll be send and saved into the backend. once all students have answered, backend will communicate that to frontend. you can click the next button to go to the next question (for developmental purposes only!).
as for right now, it is mostly frontend-backend communication work. mainly, some ground work for the main game.
there is an error? where you refresh student-answer screen, it'll disconnect you from the socket and throw an error. another problem is that some students from previous games can be in your …
=> in-game student answer questions

app/questiontimer.tsx, app/reading.tsx, app/rules.tsx
4/4/25: removed header for task #64, removed header for task #63, updated rules page task task #103
=> updates to task #64, task #63, & task #103

app/answerchoices.tsx, app/index.tsx, app/teacherwaiting.tsx, backend/backend-server.js
fixes:
- routing issues with student when the "let's go" button is pushed -> now, reliably routes both teacher and student to respective pages when the button is pressed
- the teacher waiting room continuing to play after the "let's go" button is pressed -> now, turns off waiting music when the button is pressed so that question sound and TTS can be heard clearly.
=> Lets go button patch

app/teacherwaiting.tsx
Fixed the animation for the teacher side waiting room.
=> Fixed Animation for teacher waiting room

app/_layout.tsx, app/createdecks/[id].tsx, app/index.tsx, backend/backend-server.js
Added:
- checkboxes to edit decks
- all saved decks are loaded with checkboxes ->  if answer is set as correct, checkbox is prechecked; if not, checkbox remains unchecked
- updated the backend GET and PUT request handlers to handle correct/incorrect from /createdecks/[id]
=> Edit decks patch

app/answerchoices.tsx, app/reading.tsx
Here is the file that I worked on. It seems no problem on my end.
=> Reload due to bug

app/correct.tsx, app/endgame.tsx, app/review.tsx, app/useWebSocketStore.ts, app/webSocketService.ts, backend/backend-server.js
How it works:
- student gets a question correct
- backend generates a random number 1 through 100 (inclusively)
- that number is then used to decide what powerup the user gets based on % probabilities for each powerup
- powerup chosen is then sent to frontend and is displayed on /correct screen
Notes:
- powerup decision takes into account whether or not student is in first place so that it can give the appropriate powerup (no steal powerups for first place)
- random powerup generation will work for all games user joins
=> Added power up generator

app/_layout.tsx, app/index.tsx
4/17/25: updated index page which has been reformatted to display a two-button option
=> update for task #126

.github/workflows/backend.yml, .github/workflows/development.yml, .github/workflows/production.yml, app/.gitignore, app/answerchoices.tsx, app/createdecks.tsx, app/createdecks/[id].tsx, app/login.tsx, app/questiontimer.tsx, app/reading.tsx, app/signUp.tsx, app/slogin.tsx, app/studentClicks.tsx, app/view-decks.tsx, app/webSocketService.ts, backend/backend-server.js, backend/package-lock.json, package-lock.json
4/18/25: Completed CI/CD pipeline for frontend, backend, and dev site. Test content in index file to be removed upon successful deployment. A config.ts file in ./app is now required to successfully run this code, even in localhost.
=> Implement CI/CD pipeline

app/answerchoices.tsx, app/finalscorers.tsx, app/review.tsx, app/useWebSocketStore.ts, app/webSocketService.ts, backend/backend-server.js
This loads all of the student answer info into the review page for students to review.
Some notes:
- loading of student answer info is done through a GET request to the database with a (new) table room_students schema. this table is independent from the tbl_room as it gets deleted once the the teacher socket hits the /finalscorers page. 
- If an question has multiple correct answers, only one will show (visual issue - nothing is affected). Having all correct answers shown on the review page will need a bit of restructuring of the /answerchoices socket work and room_students schema which can take some time to complete.
What to look out for:
- Double ding? encountered it once but never again
- Not routing to /studentClicks for each question -> only happened when student from 2 games ago …
=> Added end-game review page handling

app/index.tsx
Reverts E-Warren/Tappt_Group8#153
=> Revert Renu's "test sample changes"

app/answerchoices.tsx, app/index.tsx
4/22/25: updates to task #127: answer choices. answer screen layout has been modified to have the question displayed on the left panel and an enlarged diamond displayed on the right panel.
=> updates to task #127: answer choices

app/answerchoices.tsx, app/createdecks/[id].tsx, app/endgame.tsx, app/finalscorers.tsx, app/login.tsx, app/roundScorers.tsx, app/roundend.tsx, app/slogin.tsx, app/studentClicks.tsx, app/teacherwaiting.tsx, app/useWebSocketStore.ts, app/view-decks.tsx, app/webSocketService.ts, backend/backend-server.js, backend/package-lock.json
4/24/25: Implemented the end-of-round and end-of-game leaderboards. Rewires the current students array to use objects, and includes handling for reasonable output with anticipated inputs and some unconventional inputs (empty games, games with fewer than 3 players, etc). Completes issues #111 and #80.
=> Leaderboard implementation

app/roundScorers.tsx, app/webSocketService.ts
Fixing cross-game multiplier persistence, fixing one header, and slightly adjusting power-up probabilities
=> Multiplier patch

app/review.tsx
Review page TTS
- Use "f" button for the move next button 
- Repeat question (looping)
- Read the correct or incorrect answer before reading the question.
=> Review page TTS update

app/rules.tsx
4/28/25: updated rules page for task #125
=> task #125: rules page

app/finalscorers.tsx, app/questiontimer.tsx, app/roundScorers.tsx, app/roundend.tsx, app/studentWaiting.tsx, app/teacherwaiting.tsx, app/view-decks.tsx, app/webSocketService.ts, backend/backend-server.js
This PR includes the code to be able to host multiple games across different devices. It is possible to host multiple games on 1 device however, you must be careful to not run any sound at the same time (cannot run the speech as well as a correct screen sound - they will interrupt each other and cause a freeze). This code includes the patch to be able to host along with safari. This code also includes an updated alert so that students cannot join a game after it has already started. Finally, the back arrows can now be used to have a student leave the waiting room or to have the teacher remove the room in teacherWaiting. 
This PR Closes #144
=> Multiple games

app/review.tsx
I order them in ascending order.
=> ordered in(correct) questions in ascending order
